### ISSUE TITLE
Unintended encoding conversion when saving the output of the service-call

### ISSUE THREAD

**Issue by dimitry12** [Unicity/Gauntlet#13]
See `service=GetCustomerTreeDetails/Hydra-API/InfoTrax-API.t1`

I confirmed that service-output actually matches the output in the test. At the same time, the output-file stored in S3 is different from actual service output (as diff in Travis shows).

**Comment by powerc9000** [comment]
fixed b6db0dea1ab4e5369110be083d665bf535158ad4

**Comment by bluetechy** [comment]
@powerc9000 This issue still appears to be happening.

If possible before closing an issue, let's assign it to someone other than the fixer to test it and who will then close the issue.  Can you also check my permissions on this repo so that I can assign and close issues?

**Comment by powerc9000** [comment]
Can you re-run the test. I had forgotten to publish the change to NPM

**Comment by powerc9000** [comment]
@bluetechy yeah it looks like it is now passing `service=GetCustomerTreeDetails/Hydra-API/InfoTrax-API.t1 passed` I added you as a collaborator with admin rights.

**Comment by bluetechy** [comment]
@powerc9000 It looks to be working now. Thanks!  And thanks for fixing my permissions.  This issue looks to be fixed now.
