### ISSUE TITLE
Check status code

### ISSUE THREAD

**Issue by bluetechy** [Unicity/Gauntlet#24]
@powerc9000 Can we add a parameter in the config file to specific what the `expected` status code should be upon the response and then test against that value instead of only testing against a status code of 200?

* https://github.com/Unicity/Gauntlet/blob/master/test_runner.js#L151-L154

Essentially, we can override a status code of 200 for whatever value we want.  In the case that I am wanting to test right now, I would like to expect a status code of 500 and its response text and currently there is no way to do that since it requires that a good response is always a 200.

**Comment by bluetechy** [comment]
Here is an example of what I was thinking the config might look like:
````
{
"name": "t3",
"files": {
	"inputs": "input.json",
	"output": "output.txt"
},
"status": 500,
"ms": 60
}

````

**Comment by powerc9000** [comment]
This is now available

**Comment by bluetechy** [comment]
@powerc9000 Great!!!! I will test it out and then close if it works good.  Thanks!

**Comment by bluetechy** [comment]
@powerc9000 It looks like the 500 status code is now being compared, but the output message is not being compared.

**Comment by powerc9000** [comment]
@bluetechy should the test be failing and isn't? From the standpoint of the code, everything _should_ be working the same.

**Comment by bluetechy** [comment]
@powerc9000 It is as though the test is not reported at all.  `t1` and t2` are written to the screen, but `t3` is not.
