### ISSUE TITLE
Replace Google short links with another service

### ISSUE THREAD

**Issue by bluetechy** [Unicity/Gauntlet#37]
Google is stopping their support for their short link API (see https://developers.google.com/url-shortener/v1/getting_started).  We need to replace these links with another service.  I believe Chris did some recent work on this for the front-end, which we might be able to use as well on the backend.

**Comment by lukecfairchild** [comment]
I have made a branch that replaces the google api with one from rebrandly.com instead. Tomorrow we will talk with Dzmitry if we should use this 3rd party service, use a in-house one, or remove the shortener all together.

**Comment by bluetechy** [comment]
@lukecfairchild Ask Chris about the service he created.  I don't think we need to use rebrandly.com and pay a premium.  If Chris' project doesn't satisfy our needs, let's go ahead and create a simple service using our Postgres database or fork Chris' project and customize it for our needs.

**Comment by bluetechy** [comment]
@lukecfairchild It is one of these two projects:

* https://github.com/Unicity/shortlink.serverless
* https://github.com/Unicity/shortlink.express

**Comment by bluetechy** [comment]
@lukecfairchild Do we need to make any changes to MappingService and/or OrderCalc.php, which utilize this project?  If so, would you update those projects accordingly?

**Comment by lukecfairchild** [comment]
Shouldn't have to. I just removed support for a specific arg. Even if those services use the url shortener it should just be ignored. Now if they have it and we don't want to keep the deprecated part in there then yeah we should update it. I'll take a look cause I am not a fan of leaving deprecated stuff in, even if it's ignored.

**Comment by bluetechy** [comment]
@lukecfairchild I just ran a test and it appears that we are still see the google links when running gauntlet via Travis-CI.  I suspect that we need to update the npm package online.

See https://travis-ci.com/Unicity/Octopus/jobs/154584376

<img width="1000" alt="screen shot 2018-10-26 at 4 42 50 pm" src="https://user-images.githubusercontent.com/6248629/47595630-8ce7c780-d93e-11e8-9017-26776daec475.png">

I have created a branch in Octopus entitled `matthew/gaunlet_37` which you can use to test with if need be, but I believe once you update the package then you can just rerun the Travis-CI job that I mention above and it should show the new shortlink.

**Comment by bluetechy** [comment]
Here are the relevant links in Octopus:

* https://github.com/Unicity/Octopus/blob/master/components/services/MappingService/Makefile#L36-L43
* https://github.com/Unicity/Octopus/blob/master/components/services/MappingService/Makefile#L91-L92
* https://github.com/Unicity/Octopus/blob/master/components/services/MappingService/Makefile#L126-L127
* https://github.com/Unicity/Octopus/blob/master/components/services/OrderCalc.php/Makefile#L36-L43
* https://github.com/Unicity/Octopus/blob/master/components/services/OrderCalc.php/Makefile#L90-L91
* https://github.com/Unicity/Octopus/blob/master/components/services/OrderCalc.php/Makefile#L119-L120

**Comment by lukecfairchild** [comment]
@bluetechy I didn't have to change any of the used modules as it was just making a post request to google. So if It is not using the latest code that would make me think that it is either caching or has not been updated the way it needs to be. When you run those tests where is it pulling gauntlet from? It's github repo? Or some other location? If it is from some other location we need to update it there as well.

**Comment by bluetechy** [comment]
@lukecfairchild As we talked, gauntlet is a public repo so we want to make sure that anyone can use it without having to use Unicity's specific short-link service but they can customize it easily for their use so as you recommended let's abstract out the configurations and response callback part.  The next step would be to get MappingService and OrderCalc switched over to use the changes you make in Travis-CI.

**Comment by lukecfairchild** [comment]
I have added a API layer for users to add in their own request and callback for doing url shortening. If nothing is provided it is not used.

**Comment by bluetechy** [comment]
@lukecfairchild @michaelwi According to Google's short link site (https://goo.gl/), this service has been turned off.  This is now hindering development.

```
On March 30, 2018, we turned down support for goo.gl URL shortener. From April 13, 2018, only existing users were able to create short links on the goo.gl console. Analytics data was available for up to one year, until March 30, 2019, when goo.gl was discontinued. Previously created links will continue to redirect to their intended destination. Please see this blog post for more details.
```
