### ISSUE TITLE
Provide a way to add a note about what a test is being used to test

### ISSUE THREAD

**Issue by bluetechy** [Unicity/Gauntlet#7]
It would be helpful to have a way to note what each test is testing. Currently, there is no way to document a test....for instance:

````
"inputs": {
    "t1": "input.json",
    "t2": "input.json"
},
````

It would nice to be able to do something like:

````
"inputs": {
    "t1": {"file": "input.json", "desc": "Testing for...."},
    "t2": {"file": "input.json", "desc": "Testing for...."}
},
````

**Comment by powerc9000** [comment]
@bluetechy I like the idea but there is a problem with the way you are suggesting. If a test needs to provide multiple input files it does it in the form
```
"t1": {"QVPRD": "file.json", "OTHER": "file2.json"}
```

where the key in the form field.

So I could remake the specification but then it wouldn't be backward compatible which would require a full rewrite of the testfile. 

I suppose the other thing that could be does is some sort of control character to distinguish these things. eg.

```
"t1": {"^file": "input.json", "^desc": "Testing for...."},
```

So I guess for full backward compatibility I suggest this format and would like your thoughts

```javascript

"inputs": {
    //The old way
    "t1": "file.json",
    //new way with only one input
    "t2": {"^file": "input.json", "^desc": "Testing for...."},
    //new way with multiple inputs
    "t3": {"^desc": "Someting", "QVPRD": "file.json", "SOMETHING": "file2.json"} 
},

```

**Comment by powerc9000** [comment]
@bluetechy now currently supports my suggestion.

**Comment by bluetechy** [comment]
@powerc9000 I'm of the opinion that this is a young project and is at a point of evaluation before we should be concern about `backwards compatibility` issues.  Since we do not have a following yet for this project and that we are only using this program in less than a handful of places for testing, I feel that we are still in a good place to change the schema.  I view this project in `alpha` even though we have open sourced it.  Personally, I am not a fan of the control character.  I think it would be better to modify the schema and write a simple script that we could use locally to migrate our old configs.  I prefer a migration script over a hack.

**Comment by powerc9000** [comment]
Okay, I have to agree now with you. I hated the control character when I made it. So I've been thinking about a format. 

```javascript
{
  "testGroup1": {
    "name": "Something",
    "endpoint": "/test/test/test",
    "tests":[
      //Test with form data
      {
        "name": "t1",
        "description": "something",
        "files": [
          {
            "QVPRD": "path_to_file",

          }
           "output": "somefile.json"
      },
      //Test with no form input
      {
        "name": "t2",
        "description": "other thing",
        "files": ["path_to_file"],
        "output": "something.json"
      }
    ]
  }
}
```

**Comment by powerc9000** [comment]
@bluetechy I'm going to write a conversion script to convert current test to the newer format.

**Comment by powerc9000** [comment]
e2fb386

**Comment by powerc9000** [comment]
@bluetechy what do you mean by this? Print the description in the output?

**Comment by bluetechy** [comment]
@powerc9000 I believe you addressed this issue already.  I was referencing this issue in another issue so it adds a back-reference my new issue in another repo.

**Comment by powerc9000** [comment]
@bluetechy Oh can it be closed then? Since this isn't actually a problem?

**Comment by bluetechy** [comment]
@powerc9000 It is closed.  Was closed on Jan. 11.  See above.  Even though an issue is closed, messages may still appear on the thread.

**Comment by powerc9000** [comment]
@bluetechy Im sorry I misread the issue you linked as saying this issue was open,.
